### ISSUE TITLE
floating point scale for integer values

### ISSUE THREAD

**Issue by bmwiedemann** [MaximilianMeister/nailed#1]
The pull request graph uses a floating point scale (0.75, 1.5, 2.25, 3) for number of pull-requests.
It should use an integer-only scale as there are no fractional pull-requests.

**Comment by MaximilianMeister** [comment]
seems that `morris.js` does not support a configuration for that yet.
i have added a [workaround](https://github.com/MaximilianMeister/nailed/commit/3fd629b25514a5644bd65c07f95faa57d5b62919) to simply not display non integer values.
